//-----------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs">(c) http://TfsBuildExtensions.codeplex.com/. This source is subject to the Microsoft Permissive License. See http://www.microsoft.com/resources/sharedsource/licensingbasics/sharedsourcelicenses.mspx. All other rights reserved.</copyright>
//-----------------------------------------------------------------------
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.TeamFoundation.Build.Workflow.Activities.TrackingExtensions.TrackBuildError(System.Activities.CodeActivityContext,System.String)", Scope = "member", Target = "TfsBuildExtensions.Activities.CodeQuality.StyleCop.#Scan()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "Microsoft.TeamFoundation.Build.Workflow.Activities.TrackingExtensions.TrackBuildMessage(System.Activities.CodeActivityContext,System.String)", Scope = "member", Target = "TfsBuildExtensions.Activities.CodeQuality.StyleCop.#Scan()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "StyleCop", Scope = "member", Target = "TfsBuildExtensions.Activities.CodeQuality.StyleCop.#Scan()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "SourceFiles", Scope = "member", Target = "TfsBuildExtensions.Activities.CodeQuality.StyleCop.#Scan()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "TfsBuildExtensions.Activities.BaseCodeActivity.#LogBuildError(System.String)")]
